import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/hero'
import About from '../components/about'
import WorkExperience from '../components/workexperience'

const Home: NextPage = () => {
  return (
    <div className=" bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900 snap-y snap-mandatory z-0 text-white overflow">
      <Head>
        <title>Pawandeep's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      
      <section id='hero' className=' snap-start '> 
        <Hero/>
      </section>
      <section id="about" className=' snap-center '>
        <About/>
      </section> 
      <section id="experience"className=' snap-center' >
        <WorkExperience/>
      </section>
      
    </div>
  )
}

export default Home
